name: diyet_ofisim
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core & State Management
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  provider: ^6.1.5

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_analytics: ^11.4.6
  firebase_crashlytics: ^4.3.6

  # UI Components
  circular_bottom_navigation: ^2.3.0
  flutter_chat_ui: ^2.6.0
  flutter_chat_core: ^2.0.0
  easy_date_timeline: ^2.0.9
  extended_image: ^8.2.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.7.0
  table_calendar: ^3.1.2
  intl: ^0.20.2
  uuid: ^4.4.0

  # Image & Forms
  image_editor: ^1.4.0
  image_picker: ^1.1.2
  multiselect_formfield: ^0.1.7

  # Machine Learning
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Genel
      fonts:
        - asset: assets\fonts\Genel\MavenPro-SemiBold.ttf
    - family: Kalam
      fonts:
        - asset: assets\fonts\Kalam\Kalam-Regular.ttf
    - family: Chela
      fonts:
        - asset: assets\fonts\Chela\ChelaOne-Regular.ttf
    - family: Jom
      fonts:
        - asset: assets\fonts\Jom\Jomhuria-Regular.ttf
    - family: Kavon
      fonts:
        - asset: assets\fonts\Kavon\Kavoon-Regular.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/photo/
    - assets/translations/
    - assets/
  uses-material-design: true
