name: diyet_ofisim
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get_it: ^5.0.1
  provider: ^4.3.2+2
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_storage: ^4.0.1
  firebase_database: ^4.1.1
  fluttertoast: ^7.1.1
  flutter_spinkit: ^4.1.2+1
  extended_image: ^1.1.0
  image_editor: ^0.7.3
  image_picker: ^0.6.7+11
  fancy_bottom_navigation: ^0.3.2
  dash_chat: ^1.1.15
  line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^8.10.0
  timetable: ^0.2.8
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/icons/
  
  uses-material-design: true
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
