name: diyet_ofisim
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  tflite_flutter: ^0.5.0
  multiselect_formfield: ^0.1.5
  date_picker_timeline: ^1.2.1
  #calendar_timeline: ^0.6.3
  get_it: ^5.0.3
  provider: ^4.3.2+3
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_storage: ^5.2.0
  firebase_database: ^4.4.0
  fluttertoast: ^7.1.1
  flutter_spinkit: ^4.1.2+1
  extended_image: ^1.3.0
  image_editor: ^0.7.3
  image_picker: ^0.6.7+14
  fancy_bottom_navigation: ^0.3.2
  
  dash_chat: ^1.1.15
  line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^8.10.0
  flutter_datetime_picker: 1.2.5
  #New
  table_calendar: ^2.2.3
  circular_bottom_navigation: ^1.0.1
  
  flutter:
    sdk: flutter
  flutter_localizations:    
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: Genel
      fonts:
        - asset: assets\fonts\Genel\MavenPro-SemiBold.ttf
    - family: Kalam
      fonts:
        - asset: assets\fonts\Kalam\Kalam-Regular.ttf
    - family: Chela
      fonts:
        - asset: assets\fonts\Chela\ChelaOne-Regular.ttf
    - family: Jom
      fonts:
        - asset: assets\fonts\Jom\Jomhuria-Regular.ttf
    - family: Kavon
      fonts:
        - asset: assets\fonts\Kavon\Kavoon-Regular.ttf


  assets:
    - assets/images/
    - assets/icons/
    - assets/photo/
    - assets/
    
  
  uses-material-design: true
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
