name: diyet_ofisim
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  get_it:
  firebase_core:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  provider:
  easy_localization:
  flutter_spinkit:
  dash_chat_2:
  circular_bottom_navigation:
  fluttertoast:
  image_picker:
  extended_image:
  multiselect_formfield:
  table_calendar:
  date_picker_timeline:
  calendar_timeline:
  tflite_flutter:
  image_editor:
  font_awesome_flutter:
  #fancy_bottom_navigation:
  #line_awesome_icons:
  #flutter_datetime_picker:
  flutter:
    sdk: flutter

  cupertino_icons: 

  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  fonts:
    - family: Genel
      fonts:
        - asset: assets\fonts\Genel\MavenPro-SemiBold.ttf
    - family: Kalam
      fonts:
        - asset: assets\fonts\Kalam\Kalam-Regular.ttf
    - family: Chela
      fonts:
        - asset: assets\fonts\Chela\ChelaOne-Regular.ttf
    - family: Jom
      fonts:
        - asset: assets\fonts\Jom\Jomhuria-Regular.ttf
    - family: Kavon
      fonts:
        - asset: assets\fonts\Kavon\Kavoon-Regular.ttf


  assets:
    - assets/images/
    - assets/icons/
    - assets/photo/
    - assets/translations/
    - assets/
  uses-material-design: true
